name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main # Workflow จะทำงานเมื่อมีการ push ไปที่ branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # ใช้ Ubuntu Runner ล่าสุด

    steps:
    - name: Checkout repository # ดึงโค้ดจาก Repository
      uses: actions/checkout@v4

    - name: Test (basic) - Check for essential files # ขั้นตอนการทดสอบพื้นฐาน
      run: |
        echo "Checking for essential project files..."
        # ตรวจสอบว่าไฟล์ index.html มีอยู่
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found!"
          exit 1
        fi
        # ตรวจสอบว่าไฟล์ style.css มีอยู่
        if [ ! -f "style.css" ]; then
          echo "Error: style.css not found!"
          exit 1
        fi
        # ตรวจสอบว่าไฟล์ script.js มีอยู่ (ถ้าต้องการ)
        if [ ! -f "script.js" ]; then
          echo "Warning: main.js not found, but proceeding."
          # exit 1 # uncomment this line if main.js is mandatory
        fi
        echo "Essential files found. Basic test passed."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
